"""empty message

Revision ID: be19d246dd11
Revises: 
Create Date: 2020-02-07 23:36:38.280862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be19d246dd11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(length=16), nullable=False),
    sa.Column('time', sa.String(length=8), nullable=False),
    sa.Column('clientName', sa.String(length=32), nullable=False),
    sa.Column('clientPhone', sa.String(length=13), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('about', sa.Text(), nullable=False),
    sa.Column('goals', sa.String(length=64), nullable=False),
    sa.Column('picture', sa.String(length=64), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('schedule', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clientName', sa.String(length=32), nullable=False),
    sa.Column('clientPhone', sa.String(length=13), nullable=False),
    sa.Column('dayOfWeek', sa.String(length=16), nullable=False),
    sa.Column('hour', sa.String(length=4), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    op.drop_table('teachers')
    op.drop_table('requests')
    # ### end Alembic commands ###
